apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
  namespace: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - image: go_app:latest
          imagePullPolicy: IfNotPresent
          name: go-app
          # envFrom:
          #   - configMapRef:
          #       name: app-configmap
          ports:
            - containerPort: 8080
