apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: go-app
  labels:
    app: app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    app: go-app
